# Generated by Django 4.1.8 on 2023-04-06 07:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("indexes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="uploaded_by",
        ),
    ]
