# Generated by Django 4.1.8 on 2023-04-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexes", "0003_remove_collection_author_collection_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="processing",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
